services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - mongo
    restart: unless-stopped
    
    environment:
      - DB_HOST=db
      - DB_USER=arcadia_user
      - DB_PASSWORD=arcadia_password
      - DB_NAME=page_admin
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=page_admin
      - MYSQL_USER=arcadia_user
      - MYSQL_PASSWORD=arcadia_password
      - MYSQL_ROOT_PASSWORD=root_password

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password

volumes:
  mysql_data:
  mongo_data:
